list1=list(map(int,input("enter first list of integers(space separated): ").split()))
list2=list(map(int,input("enter second list of integers(space separated): ").split()))
same_length=len(list1)==len(list2)
same_sum=sum(list1)==sum(list2)
common_values=set(list1).intersection(set(list2))
print("\n results: ")
print("same length: ",same_length)
print("same sum: ",same_sum)
print("common values: ",common_values if common_values else "no common values")
